name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PREFECT__CLOUD__AUTH_TOKEN: ${{ secrets.PREFECT_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Shared Tasks
        run: | 
          pip install pytest
          pip install .

      - name: Run tests
        run: py.test tests

      - name: Build and Upload Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker build -t jcrist/prefect-github-example:latest .
          docker push jcrist/prefect-github-example:latest

      - name: Register Flows
        if: github.ref == 'refs/heads/master'
        run: prefect register flow --file flows/github_stars.py --project testing
